//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBookShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternetBookShop_KyrcahEntities : DbContext
    {
        private static InternetBookShop_KyrcahEntities _context;

        public InternetBookShop_KyrcahEntities()
            : base("name=InternetBookShop_KyrcahEntities")
        {
        }

        public static InternetBookShop_KyrcahEntities GetContext()
        {
            if (_context == null)
                _context = new InternetBookShop_KyrcahEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<addresses> addresses { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Coupons> Coupons { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Favourities> Favourities { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<jobs> jobs { get; set; }
        public virtual DbSet<order_status> order_status { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Products_in_order> Products_in_order { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<returns> returns { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<shopping_cart> shopping_cart { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
