//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBookShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shopping_cart()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int cart_id { get; set; }
        public Nullable<decimal> summ { get; set; }
        public Nullable<int> products_in_orderID { get; set; }
        public Nullable<int> discountID { get; set; }
        public Nullable<int> couponID { get; set; }
    
        public virtual Coupons Coupons { get; set; }
        public virtual Discounts Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Products_in_order Products_in_order { get; set; }
    }
}
